
shallow_clone: true

platform:
  - x86
  - x64

build_script:
  - python build_system/appveyor.helper.py 

configuration:
  - Debug
  - Release

build:
  parallel: true
  verbosity: minimal

deploy: off
